ready-made website
RomanK17/starter pull request #1
Opened 2023-03-09 07:53 UTC by RomanK17

2023-03-09 14:41 UTC, andrey-kudinov requested changes

2023-03-09 16:15 UTC, andrey-kudinov commented on styles.css
> +line-height: 16px;
`lh` не может быть меньше размера шрифта

я думаю это ошибка в дизайне

2023-03-09 16:18 UTC, andrey-kudinov commented on styles.css
> +h1 {
Старайся пж не обращаться к элементам по тегам
Используй пж классы для этого
Иначе в большом проекте обращение по тегам может вызвать сложности со стилизацией

2023-03-10 07:40 UTC, RomanK17 commented on styles.css
> +body {
Имеется в виду перед каждым блочным элементом?

> Используй пж вертикальные отступы между блоками Так твой код будет более читаемым
> 
> ```
> h1 {
>   ...
>   ...
> }
> 
> h2 {
>   ...
>   ...
> }
> 
> h3 {
>   ...
>   ...
> }
> ```

2023-03-12 10:47 UTC, andrey-kudinov commented on index.html
> +        <div class="block__item block___item_color">
Я думаю тут небольшая опечаточка
Так же не совсем понял про color - это модификатор?

2023-03-14 12:57 UTC, merged